### PR TITLE
properly initialize the cov_position matrix to zero in convertToUTM

### PR DESCRIPTION
**Pull request by doudou**

### CODE REVIEW

**Comment by doudou** [comment]
@renan028 could you have a look at this one ?

**Comment by renan028** [comment]
> @renan028 could you have a look at this one ?

ok!

**Comment by renan028** [comment]
Ok, It was "nan" for all elements before.
You could use 
position.cov_position = base::Matrix3d::Zero(); 
also, right?

I would add to the test:
BOOST_AUTO_TEST_CASE(it_propagates_the_deviations)
for (int i = 0; i < 3; ++i)
        for (int j = 0; j < 3; ++j)
            if (i!=j)
                BOOST_REQUIRE_CLOSE(0, pos.cov_position(i, j), 0.0001);

I tested and it is working, but I am not able to accept the PR

**Comment by g-arjones** [comment]
You should probably add a unity test for this.

There is also: https://github.com/rock-drivers/drivers-gps_base/pull/4 that initializes it with 1's and claims to be the "proper" way... I wonder which is one is "more proper"

**Comment by doudou** [comment]
#4 initializes the diagonal with ones, which makes no sense. Why one and not 21 or .5 ?

GPS data has deviation data which are mis-named, but are basically X/Y/Z standard deviations.

The off-diagonal elements should be zero.

**Comment by doudou** [comment]
Updated with unit test, and using Eigen's Vector3d.asDiag() method.

**Comment by g-arjones** [comment]
Looks good!

**Comment by renan028** [comment]
Looks good for me too.

**Pull request merged**
